### ISSUE TITLE
Store keys safely on github / gh-Pages

### ISSUE THREAD

**Issue by chef-louis** [chingu-voyages/v45-tier1-team-05#24]
**__Feature Description__**
Some services require api-keys or credential tokens to access their data. We want to figure out how to safely store relevant keys on github or gh-pages to support the project's needs in a secure manner.

**__User Stories__**
- [ ] Identify the methodology for safely securing credentials / keys on github / gh-pages

**Comment by jclegg31** [comment]
Couple of good articles to start: 

https://dev.to/eprenzlin/env-gitignore-and-protecting-api-keys-2b9l

https://dev.to/ptprashanttripathi/how-to-hide-api-key-in-github-repo-2ik9

**Comment by chef-louis** [comment]
Came to the conclusion that our team doesn't need api-keys
